--CREATE TABLE CUSTOMER (
--    ID INTEGER IDENTITY NOT NULL PRIMARY KEY,
--    FIRST_NAME VARCHAR(50) NOT NULL,
--    LAST_NAME VARCHAR(50) NOT NULL
--);

CREATE TABLE BANK_ACCOUNT (
    ID INTEGER IDENTITY NOT NULL PRIMARY KEY,
    BANK_TYPE VARCHAR(20) NOT NULL,
    BANK_NUMBER BIGINT NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
);